// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srbicpmrmynrrciqaiqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyYmljcG1ybXlucnJjaXFhaXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDM5ODAsImV4cCI6MjA2MDQxOTk4MH0.GCtpzLsSVo-QQlAP-YoOq2lsSU7ZP1Lo6U6c6ClAG_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);